"""
Prefect UI Artifacts

Demonstrates Prefect's built-in artifact system for UI visibility:
- create_table_artifact()    -> Display tabular data in Prefect UI
- create_markdown_artifact() -> Create rich reports in Prefect UI

Question: How do I visualize pipeline results in Prefect UI?
"""

import os
import pandas as pd
from prefect import flow, task
from prefect.artifacts import create_table_artifact, create_markdown_artifact

# Get the directory where this script is located
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")


@task
def extract_and_transform() -> pd.DataFrame:
    """Extract and transform data"""
    products = pd.read_csv(os.path.join(DATA_DIR, "01_input", "products.csv"))
    sales = pd.read_csv(os.path.join(DATA_DIR, "01_input", "sales.csv"))

    merged = pd.merge(products, sales, on="id")
    merged["total"] = merged["price"] * merged["quantity"]

    print("[ETL] Transformed data:")
    print(merged)
    print()

    return merged


@task
def create_table(df: pd.DataFrame) -> None:
    """
    Create a TABLE artifact visible in Prefect UI.

    Table artifacts display structured data in tabular format,
    perfect for previewing DataFrames or metrics.
    """
    create_table_artifact(
        key="etl-output-table",
        table=df.to_dict(orient="records"),
        description="ETL pipeline output - merged products and sales"
    )

    print("[ARTIFACT] Created table artifact: 'etl-output-table'")
    print("           -> View in Prefect UI under Artifacts tab")
    print()


@task
def create_report(df: pd.DataFrame) -> None:
    """
    Create a MARKDOWN artifact visible in Prefect UI.

    Markdown artifacts are perfect for:
    - Pipeline execution reports
    - Data quality summaries
    - Model performance metrics
    """
    total_revenue = df["total"].sum()
    avg_price = df["price"].mean()
    row_count = len(df)

    markdown_content = f"""
# ETL Pipeline Report

## Summary Statistics
| Metric | Value |
|--------|-------|
| Rows processed | {row_count} |
| Total revenue | ${total_revenue} |
| Average price | ${avg_price:.2f} |

## Output Data Preview

{df.to_markdown(index=False)}

## Data Layers
- **Input**: `data/01_input/products.csv`, `data/01_input/sales.csv`
- **Output**: Prefect UI artifact

---
*Generated by Prefect ETL Pipeline*
"""

    create_markdown_artifact(
        key="etl-report",
        markdown=markdown_content,
        description="ETL pipeline execution report"
    )

    print("[ARTIFACT] Created markdown artifact: 'etl-report'")
    print("           -> View in Prefect UI under Artifacts tab")
    print()


@flow
def etl_with_ui_artifacts() -> None:
    """
    ETL Pipeline with Prefect UI Artifacts

    Artifacts created:
    1. Table artifact - data in tabular format
    2. Markdown artifact - rich pipeline report
    """
    print("=" * 50)
    print("ETL PIPELINE - Prefect UI Artifacts Demo")
    print("=" * 50)
    print()

    df = extract_and_transform()
    create_table(df)
    create_report(df)

    print("=" * 50)
    print("Pipeline complete!")
    print()
    print("To view artifacts:")
    print("1. Start Prefect server: uv run prefect server start")
    print("2. Open http://127.0.0.1:4200")
    print("3. Navigate to this flow run -> Artifacts tab")
    print("=" * 50)


if __name__ == "__main__":
    etl_with_ui_artifacts()
